version: '3.7'

services:
  database:
    image: 'postgres'
    container_name: database
    environment:
      POSTGRES_USER: 'postgresql'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'docker_db'
      POSTGRES_HOST: 'localhost'
      POSTGRES_PORT: '5432'
    networks:
      server:
        aliases:
          - server_bd
    volumes: 
      - 'db:/var/lib/postgresql/data'
    ports:
      - 5432:5432
  api:
    build: ./api
    restart: always
    container_name: api
    ports:
      - '5000:5000'
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgresql:root@172.20.0.2:5432/docker_db
    networks:
      server:
        aliases:
          - server_api
      client:
        aliases:
          - client_api
  bash:
    build: ./bin_bash
    container_name: bin_bash
    stdin_open: true
    tty: true
    networks:
      client:
        aliases:
          - client_bash
networks:
  server:
    name: network1
    driver: bridge
    ipam:
      driver: default
  client:
    name: network2
    driver: bridge
    ipam:
      driver: default
volumes: 
  db:  
